version: "3.9"

services:
  android-studio:
    build: .
    container_name: android-studio
    restart: "no"
    privileged: false
    environment:
      - DISPLAY
    volumes:
      - "${HOME}:/home/android-studio"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
      - "/dev/bus/usb:/dev/bus/usb"
      - ${HOME}/AndroidStudioProjects:/home/AndroidStudioProjects
    network_mode: host