version: "3.7"

services:
  android-studio:
    container_name: android-studio
    image: alexandreoda/android-studio
    environment:
      - DISPLAY
    volumes:
      - "${HOME}:/home/android-studio"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
      - "/dev/bus/usb:/dev/bus/usb"
    network_mode: host